### ISSUE TITLE
pushover.pl in Weechat script repository not working

### ISSUE THREAD

**Issue by anders-dc** [stfnm/weechat-scripts#24]
Hi,

I'm using Weechat 1.0.1 with pushover.pl 1.4 installed through the Weechat script repository (`/script install pushover.pl`). Since February 21 2017 the script has stopped working. When using `plugins.var.perl.pushover.verbose = 2` I get the following message:

    [pushover] Error:
    url:https://api.pushover.net/1/messages.json 0
    {"message":"cannot be blank","errors":["message cannot be blank"],"status":0,"request":"77bb4803-4dc4-48e0-b25e-7abaae5f589c"}

Maybe this is fixed in the newer version of pushover.pl in this Github repository? If so, would you mind updating the version in the Weechat repository? https://weechat.org/scripts/source/pushover.pl.html/

Thank you!

**Comment by stfnm** [comment]
Hey there. Yeah, it's already been fixed and the upstream pull request is pending:

https://github.com/weechat/scripts/pull/195

So in the meantime you can just update to this repo's version manually. :)

**Comment by anders-dc** [comment]
Fantastic, thank you!
