### ISSUE TITLE
Black list for private messages

### ISSUE THREAD

**Issue by flaf** [stfnm/weechat-scripts#25]
Hi,

Thx for this very useful script. It could it be handy to have a black list for private messages with something like:

```
/set plugins.var.perl.pushover.blacklist "a-painful-colleague,another-painful-colleague"
```

No?

Sorry, I'm unable to implement that properly.
Regards.

**Comment by flaf** [comment]
Oops, of course the parameter `plugins.var.perl.pushover.blacklist` is already used (for channels) but maybe with an additional parameter like `plugins.var.perl.pushover.blacklist_private_msg`?

**Comment by stfnm** [comment]
The option ```plugins.var.perl.pushover.blacklist``` works for any kind of buffers, that includes private buffers just as well as channel buffers.

**Comment by flaf** [comment]
Ah...
I'm sorry, I have probably made something wrong... I have a user `totoa_` connected on Freenode (I use https://webchat.freenode.net/ to make tests) and I talk with my self (`flaf`, which is my nickname on Freenode) via a `/query flaf` and I still have notifications with this conf:

```
plugins.var.perl.pushover.blacklist         string   "freenode.totoa_"                 
plugins.var.perl.pushover.enabled           string   "on"                              
plugins.var.perl.pushover.free_pass         string   "xxxx......"                  
plugins.var.perl.pushover.free_user         string   "xxxx......."                        
plugins.var.perl.pushover.nma_apikey        string   ""                                
plugins.var.perl.pushover.only_if_away      string   "off"                             
plugins.var.perl.pushover.only_if_inactive  string   "on"                              
plugins.var.perl.pushover.pb_apikey         string   ""                                
plugins.var.perl.pushover.pb_device_iden    string   ""                                
plugins.var.perl.pushover.priority          string   ""                                
plugins.var.perl.pushover.rate_limit        string   "1"                               
plugins.var.perl.pushover.redact_priv_msg   string   "off"                             
plugins.var.perl.pushover.service           string   "freemobile"                      
plugins.var.perl.pushover.short_name        string   "on"                              
plugins.var.perl.pushover.show_highlights   string   "on"                              
plugins.var.perl.pushover.show_priv_msg     string   "on"                              
plugins.var.perl.pushover.sound             string   ""                                
plugins.var.perl.pushover.token             string   "xxxxxxxxxxxx.."  
plugins.var.perl.pushover.user              string   ""                                
plugins.var.perl.pushover.verbose           string   "2"                               
```

Have I missed something?

PS: my version of pushover.pl is 2.0

**Comment by stfnm** [comment]
Yeah the buffer name isn't quite correct, try ```/set plugins.var.perl.pushover.blacklist irc.freenode.totoa_```. You can display the full name of a buffer with ```/buffer get full_name```.

**Comment by flaf** [comment]
Ah ok, sorry. I used the ouput of `/buffer get name` not `full_name`. With `full_name` it works **perfectly**. 👍

@stfnm: sorry again for the noise and thank you for the help.
